// Job Params
// Requires: PYTEST_OPTIONS
// Optional: AWS_SSH_PEM_KEY, AWS_SSH_KEY_NAME, DEBUG

node {
  def rootPath = "/src/rancher-validation/"
  def testContainer = "${JOB_NAME}${env.BUILD_NUMBER}_test"

  def setupResultsOut = "setup-results.xml"
  def testResultsOut = "results.xml"
  def imageName = "rancher-validation-${JOB_NAME}${env.BUILD_NUMBER}"
  def setupImageName = "rancher-validation-setup-${JOB_NAME}${env.BUILD_NUMBER}"
  def deleteContainer = "${JOB_NAME}${env.BUILD_NUMBER}_delete"
  def testsDir = "tests/v3_api/"

  def deployPytestOptions = "-k test_deploy_rancher_server"
  def deletePytestOptions = "-k test_delete_rancher_server"
  def deleteResultsOut = "delete-results.xml"
  def envFile = ".env"
  def rancherConfig = "rancher_env.config"

  def branch = "master"
  if ("${env.branch}" != "null" && "${env.branch}" != "") {
    branch = "${env.branch}"
  }

  wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'XTerm', 'defaultFg': 2, 'defaultBg':1]) {
    stage('Checkout') {
      deleteDir()
      checkout([
                $class: 'GitSCM',
                branches: [[name: "*/${branch}"]],
                extensions: scm.extensions + [[$class: 'CleanCheckout']],
                userRemoteConfigs: scm.userRemoteConfigs
              ])
    }

    stage('Configure and Build') {
      if (env.AWS_SSH_PEM_KEY && env.AWS_SSH_KEY_NAME) {
        dir(".ssh") {
          def decoded = new String(AWS_SSH_PEM_KEY.decodeBase64())
          writeFile file: AWS_SSH_KEY_NAME, text: decoded
        }
      }
      sh "./tests/v3_api/scripts/configure.sh"
      sh "./tests/v3_api/scripts/build.sh"
    }
    try {
      stage('Run Validation Tests') {
        try {
          // deploy rancher server
          sh "docker run --name ${setupContainer} -t --env-file ${envFile} " +
             "${imageName} /bin/bash -c \'pytest -v -s --junit-xml=${setupResultsOut} " +
             "${deployPytestOptions} ${testsDir}\'"

          // copy file containing CATTLE_TEST_URL & ADMIN_TOKEN and load into environment variables
          sh "docker cp ${setupContainer}:${rootPath}${testsDir}${rancherConfig} ."
          load rancherConfig

          // run tests
          sh "docker run --name ${testContainer} -t --env-file ${envFile} " +
             "${imageName} /bin/bash -c \'export CATTLE_TEST_URL=${env.CATTLE_TEST_URL} " +
             "&& export ADMIN_TOKEN=${env.ADMIN_TOKEN} && pytest -v -s --junit-xml=${testResultsOut} " +
             "${PYTEST_OPTIONS} ${testsDir}\'"
        } catch(err) {
          echo 'Test run had failures. Collecting results...'
        }
      }

    stage('Delete Rancher Server') {
          try {
            if (env.RANCHER_DELETE_SERVER.toLowerCase() == "true") {
              sh "docker run --name ${deleteContainer} -t --env-file ${envFile} " +
                "${imageName} /bin/bash -c \'export CATTLE_TEST_URL=${env.CATTLE_TEST_URL} && " +
                "export ADMIN_TOKEN=${env.ADMIN_TOKEN} && pytest -v -s --junit-xml=${deleteResultsOut} " +
                "${deletePytestOptions} ${testsDir}\'"
            }
          } catch(err) {
            echo "Error: " + err
            error()
            currentBuild.result = 'FAILURE'
          }
      }

      stage('Test Report') {
        sh "docker cp ${setupContainer}:${rootPath}${setupResultsOut} ."
        sh "docker cp ${testContainer}:${rootPath}${testResultsOut} ."
        sh "docker cp ${deleteContainer}:${rootPath}${deleteResultsOut} ."
        step([$class: 'JUnitResultArchiver', testResults: "**/${setupResultsOut}"])
        step([$class: 'JUnitResultArchiver', testResults: "**/${testResultsOut}"])
        step([$class: 'JUnitResultArchiver', testResults: "**/${deleteResultsOut}"])
        sh "docker rm -v ${setupContainer}"
        sh "docker rmi ${setupImageName}"
        sh "docker rm -v ${testContainer}"
        sh "docker rmi ${imageName}"
        sh "docker stop ${deleteContainer}"
        sh "docker rm -v ${deleteContainer}"
      }
    } catch(err){
      sh "docker stop ${setupContainer}"
      sh "docker rm -v ${setupContainer}"
      sh "docker rmi ${setupImageName}"
      sh "docker stop ${testContainer}"
      sh "docker rm -v ${testContainer}"
      sh "docker rmi ${imageName}"
      sh "docker stop ${deleteContainer}"
      sh "docker rm -v ${deleteContainer}"
    }
  }
}